spring:
  mvc:
    format:
      time: HH:mm:ss
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  application:
    name: PizzaProject
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: 'true'
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  datasource:
    password: admin
    username: root
    url: jdbc:mysql://localhost:3306/pizza_project
payment-service:
  baseUrl: http://localhost:8081/api/payments
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        aop: DEBUG
server:
  servlet:
    context-path: /api
  port: '8080'
